<template>
  <ChartMetricContainer
    class="w-full min-h-0 self-start"
    title="AI Generated Revenue"
    subtitle="Revenue generated by AI agents"
    :collapsible="false"
    :loading="loading"
  >
    <template #headerAside>
      <div class="flex items-center gap-2 justify-end flex-wrap">
        <!-- Breakdown select -->
        <select
          v-model="selectedBreakdown"
          class="rounded-xl border border-[var(--kiut-border-light,#d1d5db)] bg-[var(--kiut-bg-card,#ffffff)] px-3 py-2 text-sm text-[var(--kiut-text-primary,#111827)] dark:border-[var(--kiut-border-light,#374151)] dark:bg-[var(--kiut-bg-card,#111827)] dark:text-[var(--kiut-text-primary,#f9fafb)]"
          @change="emitChangeBreakdown"
        >
          <option value="all">All</option>
          <option value="payment_method">Payment Method</option>
          <option value="agent_type">Agent Type</option>
          <option value="channel">Channel</option>
          <option value="channel_and_agent">Channel &amp; Agent</option>
        </select>

        <!-- Currency toggle: hidden when airline only uses USD -->
        <div
          v-if="localCurrency !== 'USD'"
          class="flex rounded-xl border border-[var(--kiut-border-light,#d1d5db)] bg-[var(--kiut-bg-card,#ffffff)] p-[3px] dark:border-[var(--kiut-border-light,#374151)] dark:bg-[var(--kiut-bg-card,#111827)]"
        >
          <button
            v-for="opt in currencyOptions"
            :key="opt.value"
            class="rounded-[9px] px-3 py-1 text-xs font-medium transition-all"
            :class="
              selectedCurrency === opt.value
                ? 'bg-white shadow-sm text-[var(--kiut-text-primary,#111827)] font-semibold dark:bg-[#1f2937] dark:text-[var(--kiut-text-primary,#f9fafb)]'
                : 'text-[var(--kiut-text-secondary,#6b7280)] dark:text-[var(--kiut-text-secondary,#9ca3af)]'
            "
            @click="selectedCurrency = opt.value"
          >
            {{ opt.label }}
          </button>
        </div>
      </div>
    </template>

    <div
      class="flex min-h-0 flex-col font-[family-name:Inter,ui-sans-serif,system-ui,sans-serif]"
      :class="props.loading ? 'flex-1' : 'w-full shrink-0'"
    >
      <Transition name="bm-fade" mode="out-in">
        <div
          v-if="props.loading"
          key="loading"
          class="bm-status shrink-0"
          aria-busy="true"
          aria-label="Loading chart"
        >
          <div class="flex-1 bm-skeleton-blink" aria-hidden="true"></div>
        </div>

        <div v-else key="content" class="w-full shrink-0 flex min-h-0 flex-col">
          <section
            v-if="dataChart.labels && dataChart.labels.length && dataChart.datasets.length"
            class="flex w-full shrink-0 flex-col gap-4 sm:gap-6"
          >
            <!-- Chart area -->
            <div class="chart-line-area flex h-[230px] w-full min-w-0 shrink-0 flex-col overflow-hidden">
              <ChartBar
                v-if="isStackedBar"
                :data="dataChart"
                :options="barChartOptions"
                :theme="theme"
              />
              <LineChart
                v-else
                :data="dataChart"
                :options="lineChartOptions"
                :theme="theme"
              />
            </div>

            <!-- CardInfo breakdown cards (hidden in "all" mode) -->
            <div
              v-if="topCards.length"
              class="grid w-full gap-3 md:gap-4"
              :style="cardInfoGridStyle"
            >
              <CardInfo
                v-for="item in topCards"
                :key="`card-${item.key}`"
                class="min-w-0"
                :color="item.color"
                :title="item.label"
                :value="item.amount"
                :subvalue="`${item.percentage.toFixed(1)}%`"
              />
            </div>
          </section>

          <section
            v-else
            class="flex min-h-[280px] flex-1 items-center justify-center"
          >
            <div class="max-w-[360px] px-4 text-center">
              <p
                class="mb-2 text-lg font-semibold tracking-tight text-[var(--kiut-text-primary,#171717)] dark:text-[var(--kiut-text-primary,#e5e5e5)]"
              >
                No revenue data available
              </p>
              <p
                class="m-0 text-sm leading-relaxed text-[var(--kiut-text-secondary,#737373)] dark:text-[var(--kiut-text-secondary,#a3a3a3)]"
              >
                No AI revenue found for the selected period. Try adjusting the date range.
              </p>
            </div>
          </section>
        </div>
      </Transition>
    </div>
  </ChartMetricContainer>
</template>

<script setup lang="ts">
import { computed, ref, toRef, watch } from "vue";
import moment from "moment";
import LineChart from "../../Line/ChartLine.vue";
import ChartBar from "../../Bar/ChartBar.vue";
import ChartMetricContainer from "../../Utils/ChartMetricContainer/ChartMetricContainer.vue";
import CardInfo from "../../Utils/CardInfo/CardInfo.vue";
import { useThemeDetection, type Theme } from "../../../../composables/useThemeDetection";

// ── Types ──────────────────────────────────────────────────────────────────

interface AiRevenueBreakdownItem {
  key: string;
  total: number;
  total_usd: number;
  percentage: number;
}

interface AiRevenueDayBreakdownEntry {
  ai_revenue: number;
  ai_revenue_usd: number;
}

interface AiRevenueByDay {
  date: string;
  ai_revenue: number;
  ai_revenue_usd: number;
  breakdown: Record<string, AiRevenueDayBreakdownEntry>;
}

interface AiGeneratedRevenueData {
  airline_name: string;
  start_date: string;
  end_date: string;
  currency: string;
  total_ai_revenue: number;
  total_ai_revenue_usd: number;
  breakdown: AiRevenueBreakdownItem[];
  ai_revenue_by_day: AiRevenueByDay[];
}

// ── Props / Emits ──────────────────────────────────────────────────────────

const props = withDefaults(
  defineProps<{
    loading?: boolean;
    data?: AiGeneratedRevenueData | null;
    breakdownBy?: string;
    theme?: Theme;
  }>(),
  {
    loading: false,
    data: null,
    breakdownBy: "all",
    theme: undefined,
  },
);

const emit = defineEmits<{
  changeBreakdown: [value: string];
}>();

// ── Internal state ─────────────────────────────────────────────────────────

const theme = toRef(props, "theme");
const { isDark, colors } = useThemeDetection(theme);

const selectedBreakdown = ref(props.breakdownBy);
const selectedCurrency = ref<"local" | "usd">("local");

const localCurrency = computed(() => props.data?.currency ?? "USD");
const activeCurrencyCode = computed(() =>
  selectedCurrency.value === "usd" ? "USD" : localCurrency.value,
);

const currencyOptions = computed(() => [
  { value: "local" as const, label: localCurrency.value },
  { value: "usd" as const, label: "USD" },
]);

const isStackedBar = computed(() => selectedBreakdown.value === "payment_method");

// ── Color palette ──────────────────────────────────────────────────────────

const palette = [
  "#a78bfa",
  "#34d399",
  "#f59e0b",
  "#60a5fa",
  "#f472b6",
  "#fb923c",
  "#4ade80",
  "#e879f9",
];

const getColor = (index: number): string => palette[index % palette.length];

// ── Formatting helpers ─────────────────────────────────────────────────────

const formatCompact = (value: number): string => {
  if (!value) return "0";
  const abs = Math.abs(value);
  if (abs >= 1_000_000) return (value / 1_000_000).toFixed(2) + "M";
  if (abs >= 100_000) return (value / 1_000).toFixed(1) + "K";
  return Math.round(value).toLocaleString();
};

const formatKey = (key: string): string => {
  if (!key || key === "unknown") return "Unknown";
  return key
    .split(/[_|]/)
    .map((w) => (w ? w.charAt(0).toUpperCase() + w.slice(1) : ""))
    .join(" ");
};

// ── Chart data ─────────────────────────────────────────────────────────────

const dataChart = ref<{ labels: string[]; datasets: any[] }>({
  labels: [],
  datasets: [],
});

const topCards = ref<
  Array<{ key: string; label: string; amount: string; percentage: number; color: string }>
>([]);

const cardInfoGridStyle = computed(() => {
  const cols = Math.min(topCards.value.length, 5);
  if (cols <= 0) return undefined;
  return { gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))` };
});

const processChartData = (data: AiGeneratedRevenueData | null): void => {
  const days = data?.ai_revenue_by_day ?? [];
  const breakdownItems = data?.breakdown ?? [];

  if (!days.length) {
    dataChart.value = { labels: [], datasets: [] };
    topCards.value = [];
    return;
  }

  const sorted = [...days].sort((a, b) => a.date.localeCompare(b.date));
  const labels = sorted.map((d) => moment(d.date).format("MMM DD"));
  const revenueField = selectedCurrency.value === "usd" ? "ai_revenue_usd" : "ai_revenue";

  if (selectedBreakdown.value === "all") {
    dataChart.value = {
      labels,
      datasets: [
        {
          label: `Revenue (${activeCurrencyCode.value})`,
          data: sorted.map((d) => Number(d[revenueField] ?? 0)),
          borderColor: palette[0],
          backgroundColor: "rgba(167,139,250,0.08)",
          fill: false,
          tension: 0.35,
          pointRadius: 4,
          pointHoverRadius: 6,
          pointBackgroundColor: "#ffffff",
          pointBorderColor: palette[0],
          pointBorderWidth: 2,
        },
      ],
    };
    topCards.value = [];
    return;
  }

  // Collect unique dimension keys ordered by aggregate total (top 7 max)
  const orderedKeys = breakdownItems
    .slice(0, 7)
    .map((b) => b.key);

  const datasets = orderedKeys.map((key, idx) => {
    const color = getColor(idx);
    const data = sorted.map((d) => {
      const entry = (d.breakdown ?? {})[key];
      return entry ? Number(entry[revenueField] ?? 0) : 0;
    });

    if (isStackedBar.value) {
      return {
        label: formatKey(key),
        data,
        backgroundColor: color,
        borderColor: color,
        borderWidth: 1,
        borderRadius: 3,
      };
    }
    return {
      label: formatKey(key),
      data,
      borderColor: color,
      backgroundColor: "transparent",
      fill: false,
      tension: 0.35,
      pointRadius: 4,
      pointHoverRadius: 6,
      pointBackgroundColor: "#ffffff",
      pointBorderColor: color,
      pointBorderWidth: 2,
    };
  });

  dataChart.value = { labels, datasets };

  // Breakdown cards (top 5)
  topCards.value = breakdownItems.slice(0, 5).map((item, idx) => {
    const amount =
      selectedCurrency.value === "usd" ? item.total_usd : item.total;
    return {
      key: item.key,
      label: formatKey(item.key),
      amount: `${activeCurrencyCode.value} ${formatCompact(amount)}`,
      percentage: Number(item.percentage ?? 0),
      color: getColor(idx),
    };
  });
};

// ── Chart options ──────────────────────────────────────────────────────────

const yTicks = computed(() => ({
  callback: (value: number | string) =>
    `${activeCurrencyCode.value} ${formatCompact(Number(value))}`,
  color: colors.value.textSecondary,
  padding: 8,
}));

const xAxis = computed(() => ({
  border: { display: false },
  grid: { color: colors.value.gridLines, lineWidth: 1, drawTicks: false },
  ticks: { color: colors.value.textSecondary, padding: 8 },
}));

const yAxis = computed(() => ({
  beginAtZero: true,
  border: { display: false },
  grid: { color: colors.value.gridLines, lineWidth: 1, drawTicks: false },
  ticks: yTicks.value,
}));

const lineChartOptions = computed(() => ({
  scales: {
    x: xAxis.value,
    y: yAxis.value,
  },
}));

const barChartOptions = computed(() => ({
  scales: {
    x: { ...xAxis.value, stacked: true },
    y: { ...yAxis.value, stacked: true },
  },
}));

// ── Watchers ───────────────────────────────────────────────────────────────

watch(
  () => props.data,
  (newData) => {
    if (newData) {
      selectedCurrency.value = newData.currency === "USD" ? "usd" : "local";
    }
    processChartData(newData ?? null);
  },
  { deep: true, immediate: true },
);

watch(
  () => props.breakdownBy,
  (newValue) => {
    selectedBreakdown.value = newValue;
    processChartData(props.data ?? null);
  },
);

watch(selectedCurrency, () => {
  processChartData(props.data ?? null);
});

const emitChangeBreakdown = (): void => {
  emit("changeBreakdown", selectedBreakdown.value);
};

defineExpose({ isDark });
</script>

<style scoped>
.chart-line-area {
  position: relative;
  min-height: 0;
}
</style>
<style>
@import "../bm-shared.css";
</style>
